# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('idGenre', models.AutoField(primary_key=True, serialize=False)),
                ('Genre', models.CharField(max_length=200)),
            ],
        ),
    ]
