# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='Genre',
            new_name='genreName',
        ),
    ]
